// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/wish/kcd/gok8s/apis/custom/v1"
	scheme "github.com/wish/kcd/gok8s/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// KCDsGetter has a method to return a KCDInterface.
// A group's client should implement this interface.
type KCDsGetter interface {
	KCDs(namespace string) KCDInterface
}

// KCDInterface has methods to work with KCD resources.
type KCDInterface interface {
	Create(ctx context.Context, kCD *v1.KCD, opts metav1.CreateOptions) (*v1.KCD, error)
	Update(ctx context.Context, kCD *v1.KCD, opts metav1.UpdateOptions) (*v1.KCD, error)
	UpdateStatus(ctx context.Context, kCD *v1.KCD, opts metav1.UpdateOptions) (*v1.KCD, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.KCD, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.KCDList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.KCD, err error)
	KCDExpansion
}

// kCDs implements KCDInterface
type kCDs struct {
	client rest.Interface
	ns     string
}

// newKCDs returns a KCDs
func newKCDs(c *CustomV1Client, namespace string) *kCDs {
	return &kCDs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the kCD, and returns the corresponding kCD object, and an error if there is any.
func (c *kCDs) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.KCD, err error) {
	result = &v1.KCD{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("kcds").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of KCDs that match those selectors.
func (c *kCDs) List(ctx context.Context, opts metav1.ListOptions) (result *v1.KCDList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.KCDList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("kcds").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested kCDs.
func (c *kCDs) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("kcds").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a kCD and creates it.  Returns the server's representation of the kCD, and an error, if there is any.
func (c *kCDs) Create(ctx context.Context, kCD *v1.KCD, opts metav1.CreateOptions) (result *v1.KCD, err error) {
	result = &v1.KCD{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("kcds").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(kCD).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a kCD and updates it. Returns the server's representation of the kCD, and an error, if there is any.
func (c *kCDs) Update(ctx context.Context, kCD *v1.KCD, opts metav1.UpdateOptions) (result *v1.KCD, err error) {
	result = &v1.KCD{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("kcds").
		Name(kCD.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(kCD).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *kCDs) UpdateStatus(ctx context.Context, kCD *v1.KCD, opts metav1.UpdateOptions) (result *v1.KCD, err error) {
	result = &v1.KCD{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("kcds").
		Name(kCD.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(kCD).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the kCD and deletes it. Returns an error if one occurs.
func (c *kCDs) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("kcds").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *kCDs) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("kcds").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched kCD.
func (c *kCDs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.KCD, err error) {
	result = &v1.KCD{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("kcds").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
