// Code generated by lister-gen. DO NOT EDIT.

package v1

// KCDListerExpansion allows custom methods to be added to
// KCDLister.
type KCDListerExpansion interface{}

// KCDNamespaceListerExpansion allows custom methods to be added to
// KCDNamespaceLister.
type KCDNamespaceListerExpansion interface{}
