// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/wish/kcd/gok8s/client/clientset/versioned/typed/custom/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeCustomV1 struct {
	*testing.Fake
}

func (c *FakeCustomV1) KCDs(namespace string) v1.KCDInterface {
	return &FakeKCDs{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeCustomV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
