// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "github.com/wish/kcd/gok8s/apis/custom/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeKCDs implements KCDInterface
type FakeKCDs struct {
	Fake *FakeCustomV1
	ns   string
}

var kcdsResource = v1.SchemeGroupVersion.WithResource("kcds")

var kcdsKind = v1.SchemeGroupVersion.WithKind("KCD")

// Get takes name of the kCD, and returns the corresponding kCD object, and an error if there is any.
func (c *FakeKCDs) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.KCD, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(kcdsResource, c.ns, name), &v1.KCD{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.KCD), err
}

// List takes label and field selectors, and returns the list of KCDs that match those selectors.
func (c *FakeKCDs) List(ctx context.Context, opts metav1.ListOptions) (result *v1.KCDList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(kcdsResource, kcdsKind, c.ns, opts), &v1.KCDList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.KCDList{ListMeta: obj.(*v1.KCDList).ListMeta}
	for _, item := range obj.(*v1.KCDList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested kCDs.
func (c *FakeKCDs) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(kcdsResource, c.ns, opts))

}

// Create takes the representation of a kCD and creates it.  Returns the server's representation of the kCD, and an error, if there is any.
func (c *FakeKCDs) Create(ctx context.Context, kCD *v1.KCD, opts metav1.CreateOptions) (result *v1.KCD, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(kcdsResource, c.ns, kCD), &v1.KCD{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.KCD), err
}

// Update takes the representation of a kCD and updates it. Returns the server's representation of the kCD, and an error, if there is any.
func (c *FakeKCDs) Update(ctx context.Context, kCD *v1.KCD, opts metav1.UpdateOptions) (result *v1.KCD, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(kcdsResource, c.ns, kCD), &v1.KCD{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.KCD), err
}

// Delete takes name of the kCD and deletes it. Returns an error if one occurs.
func (c *FakeKCDs) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(kcdsResource, c.ns, name, opts), &v1.KCD{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeKCDs) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(kcdsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.KCDList{})
	return err
}

// Patch applies the patch and returns the patched kCD.
func (c *FakeKCDs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.KCD, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(kcdsResource, c.ns, name, pt, data, subresources...), &v1.KCD{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.KCD), err
}
